//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryEntity.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wyklad2025RestStacjonarneEntities1 : DbContext
    {
        public Wyklad2025RestStacjonarneEntities1()
            : base("name=Wyklad2025RestStacjonarneEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<moduly> moduly { get; set; }
        public virtual DbSet<osoby> osoby { get; set; }
        public virtual DbSet<v_osoby> v_osoby { get; set; }
        public virtual DbSet<v_osoby2> v_osoby2 { get; set; }
    }
}
