//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryEntity.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class osoby
    {
        public long id_osoby { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
    }
}
